GPUS: '0,1'
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 4
TRAIN_PRINT_NUM: 6
DATASET:
  DATASET: 'ego4d'
  ORIGINAL_IMAGE_SIZE:
  - 512
  - 512
MODEL:
  NAME: 'ViT_Pose_3D'
  IMAGE_SIZE:
  - 256
  - 192
  NUM_JOINTS: 21
  NUM_DECONV_FILTERS:
  - 256
  - 256
  - 256
  NUM_LAYERS: 34
  BACKBONE:
    ARCH: 'large'
    EMBED_DIMS: 1024
    PATCH_SIZE: 16
    DROP_PATH_RATE: 0.5
  HEAD: 
    TYPE: 'transformerHead'
    pos_enc: null
    feat_mlp: False
    queries: 'per_joint'
    decoder_dim: 1024
    decoder_depth: 12
  EXTRA:
    HEATMAP_SIZE:
    - 16
    - 12
    SIGMA: 2
    DEPTH_DIM: 56
    HIDDEN_DIMS: 768
    LAYERS:
      - 2
      - 2
      - 6
      - 2
    MLP_RATIOS:
      - 4
      - 4
      - 4
      - 4
    DROP_RATE: 0.1
    DROP_PATH_RATE: 0.4 # 0.1
TEST:
  BATCH_SIZE: 16
TRAIN:
  BATCH_SIZE: 16
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 70
  LR: 0.0005
  LAYER_DECAY: 0.8
  WEIGHT_DECAY: 0.1
  WARMUP_EPOCH: 1
